language: c

dist: trusty

sudo: required

env:
  - PGVERSION=9.2
  - PGVERSION=9.3
  - PGVERSION=9.4

before_script:
  - export PATH=/usr/lib/postgresql/$PGVERSION/bin:$PATH
  - sudo /etc/init.d/postgresql stop
  - sudo /etc/init.d/postgresql start $PGVERSION
  - sudo apt-get install postgresql-server-dev-$PGVERSION
  - sudo apt-get install postgresql-common
  - createdb similarity_regress

script:
  - make && sudo make install DESTDIR=/
  - psql -c "CREATE EXTENSION similarity" similarity_regress
  - make installcheck
  - cat results/1*
